### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by zeroqian** [fateplayer/WoWAutoFishing#2]
前几年一直在用大佬的脚本，这次重开之后就又来了，感谢一直分享了这么多年！！！

目前的脚本无法使用，特意注册了个账号来反馈一下，有以下几个问题
1.以前运行脚本输入一段宏命令后，会切换到第一人称视角，现在只是把镜头拉近了，并没有切换到第一人称
2.我的分辨率是1920*1080的，鼠标指针只会在屏幕下端移动，就是技能栏那块
3.我手动调整视角，让鼠标指针到屏幕中央。但指针滑过鱼漂时，不会停下来了。以前是会稍稍往鱼漂右下角移动一点就停下来等待上钩的

可以的话还麻烦大佬能修正一下了，感谢感谢。

**Comment by fateplayer** [comment]
鼠标特征码已更新
使用最新的文件 [WoWAutoFishing.Q](https://github.com/fateplayer/WoWAutoFishing/blob/master/WoWAutoFishing.Q)
导入到按键精灵中运行
