### ISSUE TITLE
10.11下载的脚本，还是无法使用

### ISSUE THREAD

**Issue by zeroqian** [fateplayer/WoWAutoFishing#3]
大佬你好呀，我在上一条你的回复里下载的脚本
之前的问题依然存在
视角没有转到第1人称
鼠标只会在屏幕下方移动
我手动调整视角之后，鼠标经过鱼钩不会停下来

**Comment by fateplayer** [comment]
这个脚本只测试了正式服，如果是怀旧服需要自行调整
1、修改 第一行括号中的值，使用按键精灵中抓抓工具进行句柄抓取，替换类名和标题，能转到第一视角是就说明成功了
`hwnd = Plugin.Window.Find("waApplication Window","魔兽世界")`
2、使用按键精灵中抓抓工具采集鼠标特征码替换5、6行的值
`Shape1 = 1910922691	//鱼钩形`
`Shape2 = 10309065	//普通形`

**Comment by zeroqian** [comment]
大佬早上好，我是在正式服使用的
1。按照回复里说的使用抓抓工具，结果附件图片1里，类名和标题都跟原脚本里一样的。
![屏幕截图 2024-10-13 055047](https://github.com/user-attachments/assets/4c635dcb-a37d-4036-919d-29e098c88a6c)

运行脚本之后视角不是没变化，只是镜头拉近了，并没有拉到第1人称视角，见图片2（运行前）和3（运行后）
就算是我手动先调整到第1人称视角，再运行脚本，也还是会切换到图3的样子。
![屏幕截图 2024-10-13 055212](https://github.com/user-attachments/assets/6c10328b-eb9b-4abf-a0f4-ba1f3c6e1f79)
![屏幕截图 2024-10-13 055243](https://github.com/user-attachments/assets/90ed9b54-a729-4c8c-b775-a1d0d70404be)

鼠标是在屏幕下方移动的，图片4中红框位置
![屏幕截图 2024-10-13 055826](https://github.com/user-attachments/assets/f0f919dc-5320-4511-beb5-5c24dd712571)

2。这个有用，鼠标特征码的确跟原脚本不一样了，运行脚本后，我手动调整好视角，脚本能正常运行了
![屏幕截图 2024-10-13 055627](https://github.com/user-attachments/assets/61c61ce6-7061-4e51-9965-afa7d7733f8d)

**Comment by Tristin-C** [comment]
> 这个脚本只测试了正式服，如果是怀旧服需要自行调整 1、修改 第一行括号中的值，使用按键精灵中抓抓工具进行句柄抓取，替换类名和标题，能转到第一视角是就说明成功了 `hwnd = Plugin.Window.Find("waApplication Window","魔兽世界")` 2、使用按键精灵中抓抓工具采集鼠标特征码替换5、6行的值 `Shape1 = 1910922691 //鱼钩形` `Shape2 = 10309065 //普通形`

@fateplayer 我都替换了，但是开启脚本后鼠标在技能栏一行行扫，然后慢慢往下，始终找不到鱼鳔是为啥呀

**Comment by fateplayer** [comment]
这个是钓鱼鼠标滑动范围的问题，不是所有分辨率和地形我都做了测试，需要自行调整59-80行代码中的数值
另外听说现在打击自动化，不建议继续研究和使用

**Comment by zeroqian** [comment]
> 这个是钓鱼鼠标滑动范围的问题，不是所有分辨率和地形我都做了测试，需要自行调整59-80行代码中的数值 另外听说现在打击自动化，不建议继续研究和使用

多谢大佬提醒，这个一直是用小马甲弄的

说出来有点丢脸，大佬这脚本用了好几年了，但是这方面是真的不懂。
大佬能简单教下怎么改分辨率吗，具体我自己去试就行了，多谢了

**Comment by fateplayer** [comment]
> > 这个是钓鱼鼠标滑动范围的问题，不是所有分辨率和地形我都做了测试，需要自行调整59-80行代码中的数值 另外听说现在打击自动化，不建议继续研究和使用
> 
> 多谢大佬提醒，这个一直是用小马甲弄的
> 
> 说出来有点丢脸，大佬这脚本用了好几年了，但是这方面是真的不懂。 大佬能简单教下怎么改分辨率吗，具体我自己去试就行了，多谢了

屏幕左上角坐标是0,0，xx,yy是钓鱼时扫描第一行的起点，xh是宽度，yh是向下的高度，起点加上长和宽这样就有了一个长方形，会慢慢扫描整个区域
我是预估的长方形坐标，所以用屏幕大小除以系数弄的。你调整这4个值写死就行
